### ISSUE TITLE
Evaluation considerations for db-scheduler

### ISSUE THREAD

**Issue by rajki** [kagkarlsson/db-scheduler#100]
Hi db-scheduler team,
My team and I are evaluating available open source scheduler projects to incorporate for one of our high throughput use cases. We're looking at roughly around 50 million jobs per day, where each job is a short task execution (less than 10s). The design of db-scheduler (coupled with horizontal scaling) seems to fit the use case for us.

While evaluating db-scheduler, is there something that we need to explicitly keep in mind? If there are pointers which would help us start off on the right track, could you please let me know? Thanks in advance, any help is appreciated.

**Comment by kagkarlsson** [comment]
Hi! 
Yeah that sounds like a high-throughput case, like 600/s. db-scheduler was not designed primarily for those types of workloads so I don't really know where the practical limit is, but it may work with the volumes you are suggesting. At some point you may reach the database's transactions/second bottleneck.

For every execution, db-scheduler will 

* Update the record (in `scheduled_tasks` to "get the lock"
* Do the work
* Delete or update the record depending on your use-case

So there will be 2 COMMITs per execution. (And currently, no support for batching)

Couple of questions:
* What type of work are the tasks doing? cpu-bound?
* How many instances of the scheduler do you need to run?
* Is it possible to redesign the use-case so that every execution handles say 10 items of work?

**Comment by rajki** [comment]
Thanks for the quick response and details about the execution operations.
Answers to questions as below:
1. The tasks will be dispatching callbacks to webhooks. So, they'll be IO bound.
2. We haven't finalised on the number of instances we are going to run. But, we are open to both clustering (which db-scheduler natively supports), and also sharding (running multiple instances of the cluster each with its own DB). At the very least, it will be 3 worker instances polling from a DB for high availability.
3. I'm not exactly following this question, could you please elaborate based on point 1? That is our use case.

**Comment by kagkarlsson** [comment]
Regarding 3), it is complicating things, but, to reduce overhead per db-scheduler execution, is it possible to have each execution handle say 100 different webhook posts? (you would have to have a way to "assign" what items to handle to the execution, which could be done for example via the task-data.   (and you would have to deal with things like, what to do when 1 of the posts fail, but the rest is ok, and the post probably have to be idempotent to have this strategy feasible)

```
// pseudo code
scheduler.schedule(task.instance(<id>, new AssignedItems(1, 2, 3, 4, 5, ...)), <at-time>);
```

Since your scenario is fairly high in throughput, have you considered using some sort of message-queue?

**Comment by kagkarlsson** [comment]
So 3) is really asking, do you have a way of batching items up and creating one execution per batch instead of one execution per item?

**Comment by kagkarlsson** [comment]
What database are you using?

**Comment by rajki** [comment]
We plan to use MySQL for DB. I think batching is not something that naturally fits into the use case, but I'll explore this to check feasibility. I was checking on high level and [this doc](http://www.jonahharris.com/osdb/mysql/mysql-performance-whitepaper.pdf) mentions MySQL throughput at >1000 TPS. We're on cloud and scalable with respect to DB, so I suppose we should be safe on that front?

**Comment by kagkarlsson** [comment]
You may have to test it to find out if it works for you or not. I will be glad to help, should you run into trouble.

Another thing I have not mentioned yet is that currently, all scheduler-instances compete to get a lock on an execution (by updating the record), so there may be misses (i.e. another instance got the lock) and thus a higher number of queries/s than the best-case. I am looking at adding some metrics (micrometer) to publish data regarding hits, misses etc which might be helpful to you

Future improvements might reduce the overhead per execution and the risk of misses.

**Comment by rajki** [comment]
Thank you, glad to know that. At the moment, we're at the POC stage, so I'll keep you posted on updates/hiccups. Regarding the micrometer integration, that would be great to have. Thanks for considering it.

**Comment by evenh** [comment]
#49 is now implemented in version 7.2.

**Comment by kagkarlsson** [comment]
Also, hoping to have a beta of #108 ready soon. That should improve things a bit for high-volume use-cases (no misses) and it will also further on enable a batch-fetch optimization, reducing the amount of sql-statements and commits per execution.

**Comment by kagkarlsson** [comment]
Minor update, for reference. Doing some benchmarking for #108 .

Currently, the scheduler can manage at least 3k executions/s.  (Tested on google-sql postgres 4core)

Using a select-for-update strategy (#108 ), I was able to have it process 8-10k executions/s.

**Comment by rajki** [comment]
Hi @kagkarlsson given the comments on #108, do you recommend preferring Postgres as the datastore compared to MySQL for high throughput use cases?

**Comment by kagkarlsson** [comment]
I cannot really say which will perform better when both have select-for-update support as I do not have a baseline benchmark for mysql vs postgres (and I have mostly experience with postgres myself). 

The following is however true: Postgres has the best support for the select-for-update strategy (`skip locked` and `update ... returning ..`, no stored proc required etc) and will be the first database to get the support in db-scheduler. It would be a safer choice I think..

**Comment by rajki** [comment]
Thanks @kagkarlsson . We will benchmark our use case against both, PostgresSQL and MySQL (since that has better org-wide support internally for us).

**Comment by kagkarlsson** [comment]
Yeah if you mainly use MySQL, try that first 👍
