### ISSUE TITLE
Question about deleting of DeadExecutions

### ISSUE THREAD

**Issue by erzya** [kagkarlsson/db-scheduler#166]
I have some curiosity, regarding [this](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java#L232)  if the scheduler found unresolved tasks it deletes all tasks with this task name and it was very surprising for me. 

So as an example I use your scheduler in a way like this: I have several scheduled tasks with different id-s but with the same name  (the name its as a category mark) and task_id - it is a real task id that relates to one of my data in my table. 
The problem is if one of those tasks will mark as unresolved and has expired deadExecutionTime then I will lose all my tasks. 
I'm not sure, that I use it in a proper way but in my view, it is very dangerous. Do you have any advice regarding how to save prevent this behaviour?

**Comment by kagkarlsson** [comment]
It is true that _unresolved tasks_ are deleted after 14 days (default). It can be customized using `.deleteUnresolvedAfter(Duration)`.

But in order to have a task classified as _unresolved_, its task-name it must be unknown to the Scheduler, i.e. you have not provided it as a _known task_ (a mapping task-name -> task-implementation). Do you find this to be a bad default? An _unresolved task_ is useless to the Scheduler as it cannot be mapped to an implementation.

Dead executions is something else. It is when an execution has been picked for execution for too long without having its heartbeat updated. It is then classified as _dead_ and its DeadExecutionHandler is called, either rescheduling or deleting this single execution.

**Comment by erzya** [comment]
I see. Thanks. 

Probably my problem in my implementation. Because I have several Scheduler-s all of them work with the same source table, every one of them has their own tasks pool, so probably the tasks of other schedulers will mark as unresolved for the current scheduler thread  (and as I understand from this https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java#L140 current scheduler will try to process tasks from other schedulers too), so it can happen that the current scheduler will delete all of the tasks which belong to other schedulers because by the view of current scheduler they all are useless. 

So do I understand correctly that I need to have only one scheduler that works with the table (by "one" I mean scheduler with the same poll tasks names, not in a horizontal scaling meaning)? 
Hope I described it right and everything is clear. :)

**Comment by kagkarlsson** [comment]
Yes, instances of the Scheduler using the same table must have the same set of "known tasks", otherwise there will be trouble

**Comment by kagkarlsson** [comment]
You can have as many instances of the Scheduler you like (using the same table), but they must have the same set of known tasks

**Comment by erzya** [comment]
Got it! Thx for the clarification and quick response
