### ISSUE TITLE
Allow configuring number of due executions per poll

### ISSUE THREAD

**Issue by zendern** [kagkarlsson/db-scheduler#206]
## Issue:

I have the need to fire tasks with some buffer period in between them. Example I have `n` number of users submit requests all at exactly the same time. Even though that happened I want to be able to add "buffer" between the tasks that will now come out of the requests from the user.  

## First attempt

Initial attempt was to set `pollingInterval` and set the `upperLImits/thread pool sizes` to work out to be simply one (1) at a time. *Assumed* this would have just executed one task every poll interval. 

What actually happens and is working as expected after digging through the codebase is the library will query `n` number of times for the task due since upperLimit just controls how many due get pulled back in the currently due query. 

### Scenario : 

I have `n` number of one time tasks that could be scheduled at any given time. As these roll in I would like to use the `pollingInterval` along with probably another configuration value to limit the number of due executions that will fire at a given time. 

So say these 3 tasks have all been scheduled for the same time
Task 1 - 12-12-2021 1:00
Task 2 - 12-12-2021 1:00
Task 3 - 12-12-2021 1:00

Today what will happen is as the polling interval fires it will query for these in batches. Say i set the `upperlimit/thread pool sizes` to be be limited to one at a time. Even though that is the case it'll make 3 queries each one after another to make sure all due executions are executed. 

## The Ask: 

Add the ability to even though there are due executions out there. If i set the `upperlimit/thread pool sizes` to say 1 and a new parameter lets call it `maxExecutionsPerPoll=1` it would only execute Task 1 first, and then after the poll interval runs again it'll pick up Task 2, etc etc. 

Would require tweaking where we are doing the `possiblyMoreExecutionsInDb` check here
https://github.com/kagkarlsson/db-scheduler/blob/0670b31d95dc70a98a8e308d62dfb835d9a43711/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/FetchCandidates.java#L78

Because that is what is causing it to just keep querying until there are no more executions due. 

## Other considerations

So there is a path where we can just schedule our one time tasks to just be spaced out better. But tracking that in our application feels odd b/c now I need to query the schedule table, find the latest scheduled row and set the time out further. This then requires the table to be locked to guarantee i do in fact get the latest row and schedule the new one before another row gets entered by another process. 

Thus the thought of making the library simply only execute `n` number of due at a polling interval would be an easier way around the problem of having multiple tasks due at the same time execute in a serial fashion with buffer between. 

100% open to other ideas but wanted to start the conversation and see if this made sense to add before I go down the road of implementing something in my codebase. 

cc @kagkarlsson

**Comment by kagkarlsson** [comment]
Yeah, no matter what you set the limits to, the `executeDue` loop in db-scheduler should keep running until there is no due executions left.

The "correct way" I feel is to schedule the tasks to the correct execution-time from the start.

I am not a big fan of changing that behavior since it would be a very specific fix. You would for example not be able to use the scheduler backed by that table to anything else than that single task. If you application have other scheduling needs, you need another scheduler which is backed by another table (though that might be an acceptable trade-off, since the scheduler uses only one table). Also, I think it will only work if you run a single instance of the scheduler?

How about considering what could be done by using a `RecurringTask` as a sort of gatekeeper?

1. Create a separate table X for user-requests that need to be processed
1. Add a one-time task handler for the user-requests
1. Add a recurring task to the scheduler that every 10s:
    1. if user-requests in table table X, create correctly spaced out one-time tasks for them and delete from table X
    1. reschedule itself to the last execution-time + <time-distance> of the one-time tasks it just created
1. When the `RecurringTask` runs,  

Currently, an alternative for creating a table X is to directly create the one-time executions, but to some time in the far future (i.e. will never be run). The RecurringTask would then reschedule them, correctly spaced out.

**Comment by zendern** [comment]
@kagkarlsson thanks for the response. What you have called out as cons are 100% true and it is a case where you would now need multiple schedulers if you didn't want this behavior. I'm ok with closing this out. Just thought I'd ask because it felt simpler to implement in then the extra leg work you laid out. But we can move forward with one of those strategies.
