### ISSUE TITLE
Mutex behaviour

### ISSUE THREAD

**Issue by DrewEaster** [kagkarlsson/db-scheduler#207]
Hi there,

I was wondering whether db-scheduler has any out-the-box support for some degree of coordination in job execution. A specific requirement being something akin to mutexes, where it would be possible to ensure that only one job sharing a single mutex could be executed at the same time. 

An example of where/why this would be useful...

We have to implement jobs that hit an external, rate-limited API. The rate limits are tenant wide, and it means it would be feasible for us to have multiple jobs that are essentially exhausting the same rate limits. In that case, it would be ideal if we could flag up some jobs to have a shared mutex that meant only one job could be executed at time (within that job we could have code that ensures the rate limits aren't exceeded).

Have you come across anyone wanting to use db-scheduler in this way?

**Comment by kagkarlsson** [comment]
Hi!

Yeah, I think this use-case have been mentioned at least once before. A sort of maximum for the number of jobs of a certain type executing at the same time across all scheduler-instances. 

It is difficult to implement this in db-scheduler. 

* scheduler-instances have no knowledge of one another and do not communicate
* I do not want to introduce a new database table for this type of coordination since it is a strong goal to manage with a single table

One could check the `scheduled_tasks` table to see how many executions of this type of job is currently executing, and if too many, delay the execution. In fact, that is possible today in your `ExecutionHandler` using the `SchedulerClient`. It will not be 100% reliable and it will be a bit in-effective to keep moving execution-times. Some convenience could be built if this is an acceptable trade-off.

To have guarantees that only one job is executing, you could use something similar to a `RecurringTask`, which has a single instance (single database-record). But then you would likely need to store the data it needs in another table.

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v16.9.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v16.9.0))
