### ISSUE TITLE
Adding scheduled tasks with variable names via an API

### ISSUE THREAD

**Issue by anshumitra** [kagkarlsson/db-scheduler#211]
Hi!

I have been playing around with the tool (as part of a SpringBoot project) and wanted to know if it is possible to add schedulers with a variable name via an API. My data flow looks something like this:
1. There is an external system, which creates a new variable, with a value say `xyz` and a cron expression to run every 1 hour, `0 0 */1 * * *`
2. The external system calls the db-scheduler controller (via an API) to create a scheduled task with the name as the variable and the cron expression. The scheduler will print "Hello World"
2. db-scheduler accepts this, creates a task with the name `xyz` and cron  `0 0 */1 * * *`. It processes it once, say at 04:00, and prints "Hello World"
3. db-scheduler restarts at 04:15
4. db-scheduler must now wait till 05:00 before printing "Hello World"

I am able to create a scheduler as a bean with a pre-defined name. However, I can't seem to able to create a scheduled task with a variable name inside a controller. After the task is created, the scheduler can't find the task name, since it was a variable. Is it possible to do so?

Thanks

**Comment by kagkarlsson** [comment]
The `task-name` cannot be dynamic, it needs to be known by all scheduler-instances on startup because it maps to the implementation, i.e. the code that should be run. You would rather create several _instances_ of the same task, i.e. use different ids.

If the cron-schedule need to be dynamic you need to use a persistent schedule like in this example: https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/PersistentDynamicScheduleMain.java

And here is an example of how to use the `SchedulerClient` to add task-instances at runtime: https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/SchedulerClientMain.java#L30
