### ISSUE TITLE
Failing tasks are deleted, while rather should be repeated (postponed)

### ISSUE THREAD

**Issue by tomaszglinski** [kagkarlsson/db-scheduler#22]
just found out, that to workaround that, I need to create a new duplicate task... It should really be somehow configurable, via execute() result for example.... Any hope for a hotfix?

**Comment by kagkarlsson** [comment]
On train. It is configurable through the completion handler.

tir. 20. mar. 2018 kl. 16:14 skrev Tomek <notifications@github.com>:

**Comment by kagkarlsson** [comment]
Did you find out how to do this? If you for example look at the `OneTimeTask` is set-up with a `OnCompleteRemove` completion-handler. 

I agree with you that this is a very bad default, and I will even consider it a bug. It is being fixed in the refactoring I am working on, but for now, you could create another version of the `OneTimeTask` and supply it with a `CompletionHandler` that behaves in the way you want. `executionComplete.result` is `FAILED` when the task failed. You could for example reschedule it using some FiexedDelay schedule

**Comment by tomaszglinski** [comment]
Thanks for info, I workarounded it with try-catch and creation of new task. Will check it as it looks much better.
One related feature here would be to enable different backoff strategies, like for example retry first after 1 minute, than 10m, then 1h and then call it failed. Or fail-immediately or fail-never.

**Comment by kagkarlsson** [comment]
Yes, I think that is a good idea also. In the next version there will be a specific handler for failures: 
[FailureHandler.java](https://github.com/kagkarlsson/db-scheduler/blob/return_completionhandler/src/main/java/com/github/kagkarlsson/scheduler/task/FailureHandler.java)  (work-in-progress)

**Comment by kagkarlsson** [comment]
Also a builder-style creation of tasks would make it clearer what the "config-options" are..

**Comment by kagkarlsson** [comment]
This has been fixed in the new `3.0` release that should be available on central at any time now. For now it retries after 5 minutes on failures, but I will add backoff strategy as well.

**Comment by kagkarlsson** [comment]
I will consider this issue closed. The default has been amended. 

If you have need for a FailureHandler with a better back-off strategy, please raise a separate issue. Pull-request welcome :)
