### ISSUE TITLE
Need a better documentation or alternatives like a Discord server, irc/google groups, telegram etc.

### ISSUE THREAD

**Issue by raunak-nmbr** [kagkarlsson/db-scheduler#324]
Hello all,

We're implementing db-scheduler and are in need of a community to discuss, and understand db-scheduler in more detail. For some of us who are implementing such libraries in small organizations, often don't have an internal experienced team at hand. In such cases, an external library specific groups greatly help us expedite our learnings.

I tried searching but couldn't find anything. Would like to be a part of some discord/telegram/irc/google group and have it pointed on the main README of this library.

**Comment by raunak-nmbr** [comment]
For reference - https://github.com/evidentlyai/evidently
@kagkarlsson Would be great if db-scheduler can have this too.

**Comment by kagkarlsson** [comment]
Hi! Not sure we have the user-base to pull off a slack or a discord. It would be dependent on people other than myself answering questions I think. Google groups are more async and perhaps a better fit functionally since it is more like a forum with topics and less like a chat (like the others).
Currently questions are raised as issues in github, but I can agree that historical questions somewhat disappears.

**Comment by kagkarlsson** [comment]
On the other hand, suddenly there are two places to look for answers and followup and not one. Not sure it is worth it..

**Comment by kagkarlsson** [comment]
I have activated [Discussions](https://github.com/kagkarlsson/db-scheduler/discussions) for this repo.
