### ISSUE TITLE
MongoDB support 

### ISSUE THREAD

**Issue by syanukov** [kagkarlsson/db-scheduler#36]
Hi guys,

Any plans/wishes to step also into NoSQL world? 🙂
Frankly speaking I haven't had a look into the current code base to evaluate possible issues/tech debts/limitations/solutions etc. Just wanted to hear some notes and thoughts from more experienced maintainers and/or contributors before.

Thanks

**Comment by kagkarlsson** [comment]
Hi! `db-scheduler` has so far been targeted only at RDBMS-es because it's the database technology most commonly used, and it has familiar and well-known methods for guaranteeing update/locking by a single scheduler-instance. I am myself not familiar with MongoDB, but if there are some good mechanisms for optimistic locking, or row-level locking, then MongoDB support is feasible. I suppose the entire [JdbcTaskRepository](https://github.com/kagkarlsson/db-scheduler/blob/master/src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java) would need to be replicated in a `MongoDbRepository` then..

**Comment by kagkarlsson** [comment]
If this is implemented, I would be tempted to put it in some sort of `-contrib` artifact to start with.

**Comment by kagkarlsson** [comment]
Closing. Not on roadmap.
