### ISSUE TITLE
Can the db-scheduler still work when the clock is different between nodes ?

### ISSUE THREAD

**Issue by nature502** [kagkarlsson/db-scheduler#364]
In our case, we deploy a cron job across different nodes, and expect that the cron job is executed at most once. Firstly, we want to use ShedLock to implement this, but ShedLock is time-based and assumes that clocks on the nodes are synchronized. In the rare case of production issue,  the clocks on nodes might not be synchronized. So, does the db-scheduler still require that clocks on the nodes are synchronized ?

**Comment by kagkarlsson** [comment]
No, that should not be a problem. How much lag are we talking?

**Comment by nature502** [comment]
How long the lag is unpredictable, maybe ten minutes or one hour. Anyway, I want to know if db-scheduler won't be affected when nodes time is off-sync, I mean that the db-scheduler is independent from time lag.

**Comment by kagkarlsson** [comment]
That is a bit scary lag, but I thing db-scheduler will handle it.

Whichever runs the task (sees it as due) will also calculate the next execution-time after done and schedule it

**Comment by kagkarlsson** [comment]
> I mean that the db-scheduler is independent from time lag.

Revisiting. No it is not completely independent. If one instance has jumped 1 hour into the future, and picks the scheduled job, it will schedule the next time based on its current clock, so you might _miss_ a time defined in the schedule.

A bit hard to say what might occur when clocks are not in sync. I think actually a instance with a clock 1h into the future might see executions picked by another instance with out the time-diff as dead (outdated heartbeat), and send them to the DeadExecutionHandler, thus risking double execution.... 
We might add support for using the database-clock instead of the instance-clock to avoid this...
