### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by RLHawk1** [kagkarlsson/db-scheduler#39]
I have a large software application and I'd like to allow any part of it to schedule tasks. I'm using a custom table name, so my initial plan was to create a single static scheduler and start it and then allow any other part of the software to create a task and send it to the scheduler.

I thought I could do this by using something like
`Tasks.recurring("MyRecurringTask"), FixedDelay.ofSeconds(30)).execute( (inst, ctx) -> {
    // Do stuff
}).onStartup(getMyGlobalScheduler());`

But when I do that RecurringTask<T>.onStartup throws a null pointer exception.

Am I approaching this all wrong? Does each task need to have its own scheduler rather than having a global scheduler for all tasks?

**Comment by kagkarlsson** [comment]
Yes I think it is better and less confusing to try and use a single instance of the `Scheduler`.

Currently, the `Scheduler` must be given all mappings `task_name`->`Task` on startup. So all tasks must be known to the scheduler at startup, otherwise it will fail when it finds an execution for a task in the table for which is has no `Task`.

So your recurring task must be created before the `Scheduler` and sent in via the `.startTasks(..)` method on the builder.

I am not sure I see many alternatives. We could enable task-mappings to be added to the scheduler at runtime, but then you will have failures in Schedulers running on different hosts which do not yet have the mapping.

**Comment by RLHawk1** [comment]
Thanks for the quick response and information!

So there's no way of programmatically adding a new task to an existing scheduler?

We have a task intended to poll an external resource every 30 seconds, but my original design was to be able to have that task only be added to the scheduler if/when they enabled it and also have it easily disabled. I can obviously just make the task not do anything if disabled, but was trying to avoid any overhead if it's not enabled while also avoiding needing to restart the scheduler itself if it is re-enabled.

Am I correct in thinking that my task will need to still run every 30 seconds and simply not do anything if not enabled in the config?

**Comment by kagkarlsson** [comment]
No, not the task _definition_, i.e. implementation. Instances of a task (executions) may be of course be scheduled after it has been started.

You can add the task definition to the scheduler on startup, but not schedule any instances of the task. You then define a code-block where you check your property (pseudo-code):
```
if (enabled)
  scheduler.schedule(instance, first time);
else
  scheduler.cancel(instance)  //and for now catch the exception if it does not exist in the db.
```

**Comment by RLHawk1** [comment]
Perfect! Thank you very much! This answers my question and is working great! I really appreciate your help.

I was confusing task definitions with task instances, and also did not realize that I could put recurring task declarations in the Scheduler.create function without having to put them in the startTasks function.
