### ISSUE TITLE
Question: Adding/Edit tasks after startup

### ISSUE THREAD

**Issue by gsustalo** [kagkarlsson/db-scheduler#98]
Hello,

I'm trying to create a REST service of tasks that allows to manage them from a web application. But as you will see in the next lines I don't have clear some concepts. I would appreciate a little help.

My question is if it is possible to add, at runtime, new tasks dynamically and to retrieve them in order to edit/delete them.
In principle I was following the strategy from the web service of trying to get a generic scheduler in which to schedule the tasks. Such as this:

```
    @Override
    public void createTask(final TaskDTO task) {
       this.logger.debug("Create Task with name {}", task.getName());
        RecurringTask<Void> taskCreate = Tasks
                .recurring(task.getName(),fixedDelay(Duration.ofSeconds(10)))
                .execute((instance, ctx) -> {
                    log.info("Running NEW TASK. Instance: {}, ctx: {}", instance, ctx);
                });
       // scheduler is autowired
        scheduler.schedule(
                taskCreate.instance(taskCreate.getName()),
            task.getExecutionTime()  == null ? Instant.now() : task.getExecutionTime()
        );
    }
```

But I've changed my implementation to:

```
    @Override
    public void createTask(final TaskDTO task) {
       this.logger.debug("Create Task with name {}", task.getName());

        RecurringTask<Void> taskCreate = Tasks
                .recurring(task.getName(),fixedDelay(Duration.ofSeconds(10)))
                .execute((instance, ctx) -> {
                    log.info("Running NEW TASK. Instance: {}, ctx: {}", instance, ctx);
                });
        final Scheduler scheduler = Scheduler
                .create(dataSource)
                .startTasks(taskCreate)
                .threads(5)
                .build();

        scheduler.start();
    }
```

In both cases I get the messages:

> INFO  com.github.kagkarlsson.scheduler.TaskResolver -  Found execution with unknown task-name 'xxxxxx'. Adding it to the list of known unresolved task-names.
> WARN  com.github.kagkarlsson.scheduler.JdbcTaskRepository -  Failed to find implementation for task with name 'xxxxxx'. Execution will be excluded from due. Either delete the execution from the database, or add an implementation for it. The scheduler may be configured to automatically delete unresolved tasks after a certain period of time.

However, the task is executed correctly in the second case.

I would also like, among other things, a method for obtaining the scheduled tasks. I have it like this:
```

    @Override
    public List<TaskDTO> getTasks() {
        this.logger.debug("Get Tasks");
        List<TaskDTO> result = new ArrayList<>();
       //scheduler autowired
        scheduler.getScheduledExecutions(e -> {
            result.add(this.taskMapper.asTaskDTO(e));
        });
        return result;
    }
```
But this way, it only gives me back the ones that were scheduled at the start of the application.

**Comment by kagkarlsson** [comment]
Yeah, adding tasks at runtime is currently not supported and I think that will be difficult to achieve. The problem is that the scheduler (all schedulers) need to know how to map `task-name` -> `implementation`.  There is no way to distribute new implementations to all scheduler instances.

You can create new executions/task-instances, but the actual underlying task needs to be known by db-scheduler at startup. You can add such mappings when building the scheduler
```
RecurringTask<Void> mytask = ....

Scheduler
                .create(dataSource, mytask)
                ...
```

This would allow you to create multiple instances of those tasks at runtime (though with the same schedule)

```
scheduler.schedule(mytask.instance("another-instance", Instant.now());
```


If you want to achieve a task with a dynamic schedule, I think you can by using a variant of a `CustomTask` (https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/example/SchedulerMain.java#L44).
Save the schedule somehow as the task-data, and on completion of the task, reschedule according to the schedule determined by the task-data (lets say for example that the task-data is a Integer of fixed-delay minutes)

**Comment by gsustalo** [comment]
Ok. Thanks!
I am not clear that I need the creation of new tasks in execution, but it would be necessary to create new instances of the existing ones, as you explain. Anyway, I wanted to know before I keep trying without success... :)

**Comment by kagkarlsson** [comment]
Ok 👍 Let me know if you run into something else.

**Comment by anilganipineni** [comment]
> You can create new executions/task-instances, but the actual underlying task needs to be known by db-scheduler at startup. You can add such mappings when building the scheduler

How about adding the snippet in the Scheduler class.

    **_public void addTask(Task task) {
    	taskResolver.addTask(task);
    }_**

and then call this method before calling schedule?
